### ISSUE TITLE
screenshots on readme pls

### ISSUE THREAD

**Issue by donut2008** [BigFloppa404/To-Do_App#1]
thx

**Comment by BigFloppa404** [comment]
hmm sure but how to add. If i recall, i did not see image linking option in the cheat sheet.

**Comment by donut2008** [comment]
> hmm sure but how to add. If i recall, i did not see image linking option in the cheat sheet.

just screenshot app window and do ctrl+v while editing readme

**Comment by BigFloppa404** [comment]
hm sure. after new release, i will edit the file.

**Comment by BigFloppa404** [comment]
Done! (after months lol)
