### ISSUE TITLE
Outdated certificate

### ISSUE THREAD

**Issue by epicuristic** [BigFloppa404/To-Do_App#2]
The included certificate is valid until June 18 and is out of date.

**Comment by BigFloppa404** [comment]
By the way, I will upload a new beta release shortly, with an updated cert and known issues list, it is stable enough but has a few rough edges here and there.

**Comment by epicuristic** [comment]
Got it here, didn't know about Store. Thx.

**Comment by dongle-the-gadget** [comment]
@BigFloppa404, how about downloading the packages from Microsoft Store?

**Comment by BigFloppa404** [comment]
Hm, @FireCubeStudios manages the store version actually, he might know more.

**Comment by BigFloppa404** [comment]
But that would be the msix installer if I'm not wrong?

**Comment by dongle-the-gadget** [comment]
> But that would be the msix installer if I'm not wrong?

Well, yeah, it's MSIX.

**Comment by BigFloppa404** [comment]
I am confused lol. I'll just say, the store version won't be updated as much as this github one, however next major update will come soon to store.
