### ISSUE TITLE
Tint not transparent enough

### ISSUE THREAD

**Issue by itsWindows11** [BigFloppa404/To-Do_App#4]
The app content's tint isn't transparent enough so that mica would be visible. Here's an example:

![unknown.png](https://user-images.githubusercontent.com/81253203/185407943-ecf6e45c-ff49-4d4b-9446-6c9858df69e7.png)

**Comment by BigFloppa404** [comment]
Btw if you turn on dark mode and choose one of the black bg themes, mica shines through.

**Comment by BigFloppa404** [comment]
Fixed with commit 3021bef9b9e8628b2466715cec773752a4f4d012. Now you can change opacity, and at the same time keep the "vibrancy" of backplates.
